title: Yao Xiong
description: Long Form Jekyll theme built with SASS

url: https://yaoxiong-p.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-scholar
  
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Recent Works
      url: /recent_works
    - title: Research
    - title: Publications
    - title: Contact
      url: /contact

social:
    #github: yaoxiong-p
    orcid: 0000-0001-9350-6112
    twitter: YaoXiong_C
    #facebook: brianmaierjr
    email: yaoxiong@ucsb.edu
    linkedin: yao-xiong-cctsm
    #youtube: RickAstleyYT
    #tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: yaoxiong

# ➜ jekyll-scholar 配置（实现：ACS 样式 + 标题可点击 + 按 bib 顺序）
scholar:
  style: _bibliography/american-chemical-society.csl
  locale: en
  bibliography: _bibliography/ref.bib
  sort_by: none
  order: ascending
  bibliography_template: bib_item
